# Generated by Django 4.2.2 on 2023-07-27 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="is_completed",
        ),
    ]
