# Generated by Django 4.2.2 on 2023-07-01 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
    ]
