# Generated by Django 4.2.2 on 2023-07-17 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["pk"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
    ]
